name: home_page
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  flutter_native_splash: ^2.4.3
  get_cli: ^1.8.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # path_provider: ^2.1.5
  # # sqflite: ^2.4.1
  # # path: ^1.8.3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
          style: normal
