// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi_UoKXx5yYnnrV_6EzL7NpCpWSVSPNE',
    appId: '1:1006461101469:web:c6836e9058a032c1053b74',
    messagingSenderId: '1006461101469',
    projectId: 'motion-todo-8',
    authDomain: 'motion-todo-8.firebaseapp.com',
    storageBucket: 'motion-todo-8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-XlnUF9l15IlwnGHZC8uPWq3uumwQ2js',
    appId: '1:1006461101469:android:c846daac83aa5c43053b74',
    messagingSenderId: '1006461101469',
    projectId: 'motion-todo-8',
    storageBucket: 'motion-todo-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYouefIE0JFLwDp-Zai7w_dlz5xmUmM28',
    appId: '1:1006461101469:ios:c8f7bbda61e23b51053b74',
    messagingSenderId: '1006461101469',
    projectId: 'motion-todo-8',
    storageBucket: 'motion-todo-8.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYouefIE0JFLwDp-Zai7w_dlz5xmUmM28',
    appId: '1:1006461101469:ios:c8f7bbda61e23b51053b74',
    messagingSenderId: '1006461101469',
    projectId: 'motion-todo-8',
    storageBucket: 'motion-todo-8.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzi_UoKXx5yYnnrV_6EzL7NpCpWSVSPNE',
    appId: '1:1006461101469:web:bb221af2777a6e69053b74',
    messagingSenderId: '1006461101469',
    projectId: 'motion-todo-8',
    authDomain: 'motion-todo-8.firebaseapp.com',
    storageBucket: 'motion-todo-8.firebasestorage.app',
  );
}
